### ISSUE TITLE
InvalidPassword

### ISSUE THREAD

**Issue by cRestalious** [tacheometry/steam-hour-farmer#2]
Hello,

After running the steam-hour-farmer I keep getting that the password is wrong, I have double checked it and the password is corrent, what could be the issue?

**Comment by tacheometry** [comment]
Can you send over the `.env` file you have (with the password, etc, censored, but keep the formatting) and the logs you got?

**Comment by cRestalious** [comment]
![image](https://github.com/tacheometry/steam-hour-farmer/assets/115401374/015a68ba-46db-492e-995e-8f5ef6d22e25)
I see no logs at the moment

**Comment by tacheometry** [comment]
> ![image](https://github.com/tacheometry/steam-hour-farmer/assets/115401374/015a68ba-46db-492e-995e-8f5ef6d22e25)
> I see no logs at the moment 

There shouldn't be any `,` after each line, try removing them and see if it's working

**Comment by tacheometry** [comment]
Oh no... it's like that in the documentation... I will fix it, thank you very much for reporting this👍

**Comment by cRestalious** [comment]
Still getting the same issue, after removing these :/
![image](https://github.com/tacheometry/steam-hour-farmer/assets/115401374/a70c693f-d75d-4569-b84f-9a4aabdbbb74)

**Comment by tacheometry** [comment]
Does your password have any special characters, different than a-Z 0-9, etc?

Also can you try removing the quotes and see if it works?

Also try to remove the `SteamData` folder each time you do a trial

**Comment by tacheometry** [comment]
I'll also update the package soon with an updated Steam library, maybe that fixes it...

**Comment by cRestalious** [comment]
Yeah it does. It has !@#$%^&*() characters

**Comment by tacheometry** [comment]
Hmm... maybe it's because of the way the env library handles it, see here: https://www.npmjs.com/package/dotenv#what-rules-does-the-parsing-engine-follow

Does it have spaces at the end? I don't know of other rules that'd affect this

**Comment by cRestalious** [comment]
No spaces at the end, its weird. Maybe I have to try with a different password? But still doesn't make sense.

**Comment by tacheometry** [comment]
No `"` `\` or `'` characters either?

**Comment by cRestalious** [comment]
In the password no

**Comment by tacheometry** [comment]
Ok, let's determine if this is actually caused by the password getting parsed incorrectly from the file or not...

1. In your farmer directory, run `npm i steam-hour-farmer`
2. Edit the file `./node_modules/steam-hour-farmer/index.js`
3. Right under the line
```js
require("dotenv").config();
```
Insert the following so it looks like this:
```js
require("dotenv").config();
console.log(`PASSWORD: [${process.env.PASSWORD}]`);
```
4. Run the process using `npx steam-hour-farmer` (if you don't use `npx` it will use the global install which doesn't have modifications)
5. Check if the text between the brackets matches your password EXACTLY

If it does match, then that's not the issue, and we can try with an updated library for login...

**Comment by cRestalious** [comment]
It does match, yes

**Comment by cRestalious** [comment]
Any updates?

**Comment by tacheometry** [comment]
Alright, I've investigated quite a bit... turns out it's not related to the password itself, at all... Steam also sends out the `InvalidPassword` error (error code 5) in the cases when the access token is invalid. I don't think one is being sent right now - not sure. But here's what I've observed
- It works on my main account that uses Steam Guard ([SteamDesktopAuthenticator](https://github.com/Jessecar96/SteamDesktopAuthenticator) in this case). Even when I delete the `SteamData` directory.
- It doesn't work on my alt account that only has email based verification (I'm not sure, but this may be on by default), giving me the dreaded `InvalidPassword` error.

Currently, the CLI doesn't ask for any code received from the email (and an email isn't even being sent, because this verification isn't being requested). But running this script [here](https://github.com/DoctorMcKay/node-steam-session/blob/master/examples/login-with-password.ts) as a test, this does ask for the email code. Afterwards, the outputted access token can be used for account login.

Interestingly, when I made this project, logging in was less rigorous, and I was also testing on my alt account that only had email verification. 1 month later, that changed, apparently! But I've been running `steam-hour-farmer` without issue, non-stop, since then. It's been almost two years...

To use steam-hour-farmer _right now_, you should be fine with setting up Steam Guard (I recommend SteamDesktopAuthenticator and setting `SHARED_SECRET` so it can re-log-in by itself without any manual intervention) and running it that way. Otherwise you can try using it again after I update it to support this method as well.

Thank you for reporting the initial issue and the sustained replies 😉

**Comment by cRestalious** [comment]
Hm, thanks for the reply, I using Steam Guard but on mobile, could be that be the issue?

**Comment by tacheometry** [comment]
Shouldn't be the issue. But, are you on Windows?

**Comment by cRestalious** [comment]
Yes

**Comment by tacheometry** [comment]
Ok... now try it with the updated version. `npm i -g steam-hour-farmer@latest` should work. But delete everything in your folder other than the `.env`, and run normally.

You will also need to change `USERNAME` to `ACCOUNT_NAME`

Tell me if it works

**Comment by cRestalious** [comment]
Yep it worked. Thank you so much.

**Comment by tacheometry** [comment]
👍👍👍

On Windows, the `USERNAME` env variable is actually the Windows account name... so for me it was trying to log in with `DevAccount` (my account name) for example... I was so surprised when I found that out...

**Comment by tacheometry** [comment]
I didn't catch this initially because I made the project when I was maining Linux... disregard my other theories haha

**Comment by cRestalious** [comment]
That's interesting... Glad that it's solved now. thank you :D
